### ISSUE TITLE
support vendor custom iso

### ISSUE THREAD

**Issue by alsyundawy** [itiligent/ESXi-Custom-ISO#13]
support vendor custom iso

like dell, lenovo, hp etc custom image iso

**Comment by itiligent** [comment]
if someone can provide me with the correcrt vibs, then this is possible - I dont have the hardware to test so this would need a bit more collaboration from others.

**Comment by alsyundawy** [comment]
i have link repository custom offline zip

**Comment by itiligent** [comment]
I am hesitant to include unknown sources for an edge use case when the main purpose of this repo is for general homelab use.  

I'd consider making a Dell or HP specific ISO script, but as I am time limited, as I said before I'd need some help tracking down available trusted sources of vendor specific vibs, otherwise, you could also simply adjust the script's structure to include your own custom vibs.

**Comment by alsyundawy** [comment]
download from broadcom

**Comment by itiligent** [comment]
Please remeber this is free software, so I'm closing this due to a lack of information (and effort) in communicating any specific details of the requirement.
