### ISSUE TITLE
Requires python for absolutely no reason

### ISSUE THREAD

**Issue by trollcop** [itiligent/ESXi-Custom-ISO#7]
Why does this requirement even exist? Why would windows users need to have this useless scripting language installed?

Rewrite whatever parts rely on python in powershell. Thanks.

**Comment by itiligent** [comment]
Please be advised Python is indeed a new dependency of PowerCLI since 13.0 as [as docmented here](https://developer.vmware.com/docs/15315/GUID-9081EBAF-BF85-48B1-82A0-D1C49F3FF1E8.html)

The background here is that because AutoDeploy and ImageBuilder are now multi-platform , Python must now be installed as a prerequsite if you want to use these features.....So, for ImageBuilder to work, Python 3.7, pip, and a few other modules (as documented in the Readme) are also required.  I guess that in the datacentre, Windows is not the only use case for Admin of VSphere, and this is VMware's approach to cross platform support.

If you so strongly disagree with PowerCLI's reliance on Python, then you are quite short on options I'm afraid.
